[package]
name = "audio_playback"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "=1.0.55"
libretrogd = { path = "../../libretrogd" }
sdl2 = { version = "0.34.5", features = ["static-link", "bundled", "unsafe_textures" ] }

