[package]
name = "variable_screen_size"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "=1.0.55"
ggdt = { path = "../../ggdt" }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
